- name: Check that our targets are reachable
  hosts: webprod
  gather_facts: false

  tasks:
  #  - ping:

  - name: ICMP ping
    delegate_to: localhost
    command: ping -c 3 "{{ inventory_hostname }}"
    # Because it is an reporting task
    changed_when: false
    check_mode: false
    failed_when: router_ping.rc == 1 or router_ping.rc > 2 # will result into success for rc 0 and rc 2
    register: router_ping
  
  - name: Show Return Code
    debug:
      msg: "{{ router_ping.rc }}"

